#!/bin/bash

source config

WORKDIR=/var/guestwlan

WLANPSK=$(dd if=/dev/urandom count=1 status=none|tr -d -c 'a-z'|cut -b1-10)
sed -i -e "s/ssid=.*/ssid=${WLANSSID}/" /etc/hostapd/hostapd.conf
sed -i -e "s/wpa_passphrase=.*/wpa_passphrase=${WLANPSK}/" /etc/hostapd/hostapd.conf
service hostapd reload

qrencode -t PNG -o ${WORKDIR}/qr_android.png -v 30 -l H "WIFI:T:WPA;S:${WLANSSID};P:${WLANPSK};H:false;"
qrencode -t PNG -o ${WORKDIR}/qr_windows.png -s 4 "WIFI;T:WPA;S:${WLANSSID};P:${WLANPSK};H:false;"
sed -e "s/__wlanssid__/${WLANSSID}/g" /var/www/html/guestwlan.mobileconfig.in > /var/www/html/${WLANPSK}.mobileconfig
sed -i -e "s/<string>__wlanpsk__/<string>${WLANPSK}/" /var/www/html/${WLANPSK}.mobileconfig
qrencode -t PNG -o ${WORKDIR}/qr_ios.png -s 4 "${DOMAIN}${WLANPSK}.mobileconfig"

gm convert -page +0+0 ${WORKDIR}/qr_android.png -page +110+100 ${WORKDIR}/robot.png -mosaic ${WORKDIR}/android.png
gm convert -page +0+0 ${WORKDIR}/qr_windows.png -mosaic ${WORKDIR}/windows.png
gm convert -page +0+0 ${WORKDIR}/qr_ios.png -mosaic ${WORKDIR}/ios.png

cat > /var/guestwlan/wlan.cfg <<EOF
[WLAN]
wlanssid=${WLANSSID}
wlanpsk=${WLANPSK}
refresh=${REFRESHINTERVAL}
EOF
